In [1]:
import sys
import os
import torch
import numpy as np
from detzoo.datasets import VOCDataset, COCODataset
from detzoo.models import YOLOv1
from detzoo.utils import *
from matplotlib import pyplot as plt
import torchvision.transforms as T

voc_dataset = VOCDataset(root='../../data/VOC', 
                        year='2007',
                        image_set='train')
coco_dataset = COCODataset(root='../../data/COCO', 
                           year='2017',
                           image_set='train')

/Users/guolianglu/miniconda3/envs/detzoo/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


loading annotations into memory...
Done (t=5.75s)
creating index...
index created!
loading annotations into memory...
Done (t=6.19s)
creating index...
index created!


In [4]:
data_loader = torch.utils.data.DataLoader(voc_dataset, batch_size=1, shuffle=True)
for images, targets in data_loader:
    print(type(images), type(targets))
    print(images.shape)
    print(targets['boxes'])
    print(targets['confidences'])
    print(targets['labels'])
    break

<class 'torch.Tensor'> <class 'dict'>
torch.Size([1, 3, 448, 448])
tensor([[[  1.1947,  43.9040, 407.3813, 447.1040]]])
tensor([[1.]])
tensor([[7]])


In [ ]:
try:
    data_iter1
except NameError:
    data_iter1 = iter(voc_dataset)

img1, target1 = next(data_iter1)

plot_image_and_boxes(img1, target1, voc_dataset.classes)

In [ ]:
try:
    data_iter2
except NameError:
    data_iter2 = iter(coco_dataset)

img2, target2 = next(data_iter2)

plot_image_and_boxes(img2, target2, coco_dataset.classes)